### ISSUE TITLE
Classification for Plantae is broken

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#121]
https://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/9443092#classification

It should show all phylum values but only show random taxa:

![image](https://user-images.githubusercontent.com/532845/46188101-7e4fc580-c32a-11e8-91ee-b00ca39ab2e3.png)

**Comment by ansell** [comment]
The other entries look like they may be not linked at other levels, just from looking at a few select entries. They seem to be direct branches out from Plantae in our merged taxonomy and are probably showing us and our names suppliers some places where improvement is needed. 

However, it may be useful not to show them by default to make it possible to focus on the branches that make sense when looking at a ``kingdom``.

**Comment by nickdos** [comment]
Source of list is https://bie.ala.org.au/ws/childConcepts//http://id.biodiversity.org.au/node/apni/9443092

Seems to be coming in alphabetic order for the `name` attribute with ranks all mixed up.

**Comment by ansell** [comment]
The ``childConcepts`` list contains rankId's that are very different to the ``1000`` on https://bie.ala.org.au/ws/species/http://id.biodiversity.org.au/node/apni/9443092 possibly because they are being put there by a default placement algorithm

Would it be possible to hide the anomalous ones (difference in ``rankId``'s > 2000??) by default under a button like ``Show more`` so those that are more closely related in terms of taxonomic rank are shown by default on their own?

**Comment by nickdos** [comment]
Code fixed

**Comment by nickdos** [comment]
on test for QA

https://bie-test.ala.org.au/species/http://id.biodiversity.org.au/node/apni/9443092#classification

**Comment by ansell** [comment]
The only subcategory for Plantae now seems to be this NZOR entry, which doesn't seem to have any children and leads to a dead-end. That may not be relevant to fixing this issue specifically if it is a lower level issue with integrating NZOR and the Australian Taxonomies, but it would be useful to have the others to explore other relations. 

https://bie-test.ala.org.au/species/NZOR-4-17017#classification

Is it possible to hide the other ranks underneath a "show more" button/link that they are still accessible if necessary?

The 2000 rankId difference may currently excluding the second category down if the successive ranks are exactly 2000 apart. The comparison may need to be ``<=`` instead of ``<`` on the following line to allow the 2000 difference rankId to show up, currently it may only be allowing 1999, which may not be enough for two ranks:

https://github.com/AtlasOfLivingAustralia/bie-plugin/blob/aaedfbb66645ba09e89705fbaee0917a17a235db/grails-app/views/species/_classification.gsp#L62

**Comment by nickdos** [comment]
Good point - I assumed that was the next major classification under plantae but you're right it should list more than that. I did try `3000` but got the same result. WIll look into it more.

**Comment by nickdos** [comment]
I would expect https://bie.ala.org.au/ws/species/http://id.biodiversity.org.au/name/apni/217746.json to appear as a child taxa of Plantae but its not coming through.

**Comment by ansell** [comment]
Trimming the list being shown to users in the interface to only show close child ranks is a useful workaround for this case.

Should we close this issue as having the initial workaround implemented and open separate issues for the features and bugs that are still outstanding:

* showing the full child list regardless of ``rankid``, which some deployments may legitimately want (feature request)
* configure the rankid difference from a configuration file, which some deployments may legitimately want (feature request)
* explore why the immediate children for Plantae are incorrect in the ala names and/or bie-index (bug)
