### ISSUE TITLE
images not displaying on species pages in Internet Explorer

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/bie-plugin#134]
e.g. https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:2323e7e5-41b4-434a-b27e-75f9d2c6439f#gallery viewed in firefox or chrome shows images, in IE shows "No images available for this taxon"

from support ticket: https://support.ehelp.edu.au/a/tickets/27187

**Comment by charvolant** [comment]
Queries of the form https://biocache-ws.ala.org.au/ws/occurrences/search.json?q=lsid:urn:lsid:biodiversity.org.au:afd.taxon:2323e7e5-41b4-434a-b27e-75f9d2c6439f&fq=multimedia:"Image"&pageSize=20&facet=off&start=0&fq=type_status:*&im=true&callback=jQuery112406249824138855854_1547162609463&_=1547162609464 in IE result in a 400/Bad Request error, although the same thing in Chrome is fine.

The offending item seems to be the multimedia:"Image" since https://biocache-ws.ala.org.au/ws/occurrences/search.json?q=lsid:"urn:lsid:biodiversity.org.au:afd.taxon:2323e7e5-41b4-434a-b27e-75f9d2c6439f"&fq=multimedia:"Image"&pageSize=20&facet=off&start=0&fq=type_status:*&im=true&callback=jQuery112406249824138855854_1547162609463&_=1547162609464 is fine

**Comment by charvolant** [comment]
The problem seems to be the multimedia:"Image" in https://biocache-ws.ala.org.au/ws/occurrences/search.json?q=lsid:urn:lsid:biodiversity.org.au:afd.taxon:2323e7e5-41b4-434a-b27e-75f9d2c6439f&fq=multimedia:"Image"&pageSize=20&facet=off&start=0&fq=type_status:*&im=true&callback=jQuery112406249824138855854_1547162609463&_=1547162609464

Since

 https://biocache-ws.ala.org.au/ws/occurrences/search.json?q=lsid:urn:lsid:biodiversity.org.au:afd.taxon:2323e7e5-41b4-434a-b27e-75f9d2c6439f&fq=multimedia:Image&pageSize=20&facet=off&start=0&fq=type_status:*&im=true&callback=jQuery112406249824138855854_1547162609463&_=1547162609464

Is OK

**Comment by charvolant** [comment]
Fixed in https://github.com/AtlasOfLivingAustralia/bie-plugin/pull/135 and downstream ala-bie. Make a 1.4.11-maintenance branch to keep track of this while development continues.
