### ISSUE TITLE
Encyclopedia of Life pages sometimes returns descriptions treating native species as a pest

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-plugin#181]
See for example Phragmites australis https://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2901931#overview The first EoL article comes from the New York Invasive Species Clearing House.

I doubt that we'll ever be able to completely remove dud references from the EoL but, as a suggested solution, a blacklist?

**Comment by charvolant** [comment]
And, while I'm about it, https://bie.ala.org.au/species/NZOR-6-48824#overview returns results that suggest the Chara algae genus is actually the Chara moth genus

**Comment by nielsklazenga** [comment]
Not much wrong with the *Phragmites australis* entry. *Phragmites australis* is almost cosmopolitan, certainly not an Australian endemic. It is also native to North America, but there are non-native stands, which is what the top article in the BIE is writing about. Likewise, *Baccharis halimifolia* is native to the area where the description is from (but not to Australia).

Might be good – instead of trying to work out which descriptions are applicable to Australia and which ones are not (which seems really hard to do to me) – to clearly indicate the geographic scope for each entry and then have an ordering which goes something like `Australia national`, `Australia state`, `global`, `foreign`, so the most relevant entries are on top (you probably already have something like that).

Also, what do we need to do to get Australian descriptions into the BIE? They are available online for *Phragmites australis*, for example http://plantnet.rbgsyd.nsw.gov.au/cgi-bin/NSWfl.pl?page=nswfl&lvl=sp&name=Phragmites~australis and  https://vicflora.rbg.vic.gov.au/flora/taxon/53fba474-8d64-4488-a8d3-28b1ed218314.

**Comment by TaniaGLaity** [comment]
closing as removed links to EOL and implemented the ability for admins to assign Wikipedia pages to species overview in BIE
