### ISSUE TITLE
Legacy autocomplete URL is 404

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-plugin#55]
A few legacy systems still send a request to:

http://bie.ala.org.au/search/auto.jsonp

Which now throws a 404. 

Fix is to redirect the output of this URL to:

http://bie.ala.org.au/ws/search/auto.jsonp

either via `UrlMappings.groovy` or via a controller method.

**Comment by nickdos** [comment]
Available on test for QA

http://bie-test.ala.org.au/ws/search/auto.jsonp

NOTE that the `jsonp callback` feature is not implemented on bie-index and thus doesn't work here either, as it has been implemented as a proxy. This is only of concern to legacy apps as we are (should be) using CORS JSON only now.

**Comment by ansell** [comment]
This may also fix https://github.com/AtlasOfLivingAustralia/ala-bootstrap3/issues/8

**Comment by ansell** [comment]
The lack of JSONP support by bie-index seems to be still breaking the autocomplete by our main website search bar: ``https://bie.ala.org.au/ws/search/auto.jsonp?callback=jQuery112406428917128422043_1542757912505&q=test&limit=100&timestamp=1542757919528&_=1542757912506`` returns JSON with no wrapped callback function, which the browser fails to interpret as JSONP, even though the results seem to look okay otherwise as a JSON document. An alternative to adding/fixing JSONP in bie-index may be to focus on fixing commonui and/or ala-bootstrap and switch them over to CORS+JSON rather than JSONP, as it seems to work already that way, just that the browser is expecting JSONP and fails after the results from bie come back successfully.

**Comment by ansell** [comment]
Closing this as ``https://bie-test.ala.org.au/search/auto.jsonp?q=acaci`` works for me.
